
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryGymPlanner
{

using System;
    using System.Collections.Generic;
    
public partial class Sets
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sets()
    {

        this.Workout = new HashSet<Workouts>();

    }


    public int ID_set { get; set; }

    public Nullable<int> Num_reps { get; set; }

    public Nullable<int> Weight { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Workouts> Workout { get; set; }

}

}
