//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryGymPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дні
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Дні()
        {
            this.Тренування = new HashSet<Тренування>();
            this.Користувачі = new HashSet<Користувачі>();
        }
    
        public System.DateTime Дата { get; set; }
        public string Коментар { get; set; }
        public int ID_дня { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тренування> Тренування { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Користувачі> Користувачі { get; set; }
    }
}
