//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryGymPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Підходи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Підходи()
        {
            this.Тренування = new HashSet<Тренування>();
        }
    
        public int ID_підходу { get; set; }
        public Nullable<int> Кількість_повторень { get; set; }
        public Nullable<int> Вага { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тренування> Тренування { get; set; }
    }
}
